### PR TITLE
Wait for the DOM element, that matches the CSS selector, to be available before taking the screenshot

### PR DESCRIPTION
**Pull request by geertvanheusden**
Implementation of feature #3.

Tested on PhantomJS and SlimerJS.

### CODE REVIEW

**Comment by geertvanheusden** [comment]
@vbauer Any chance you have time to look at my PR? ;-)

**Comment by vbauer** [comment]
@geertvanheusden Great job! Thanks!

**Comment by geertvanheusden** [comment]
@vbauer Could you please release a new version that includes this PR? Thanks! :-)

**Comment by vbauer** [comment]
@geertvanheusden NP, I've just released 0.4.11: https://www.npmjs.com/package/manet

**Pull request merged**
