### PR TITLE
0 is now a valid value for the top and left values of the clip rect

### PR DESCRIPTION
**Pull request by cdunlap**
I changed the logic in the screenshot script to allow 0's for the left and top coord of the clipRect parameter. They're technically valid values for cases where you want to crop without losing any pixels from the top left corner. The width and height parameters weren't cutting it, height seemed to have no affect on the output.

### CODE REVIEW

**Comment by vbauer** [comment]
Could you please split this changes in 2 PR and revert changes in "package.json" file?

**Comment by cdunlap** [comment]
Oh weird, I didn't realize it would include the changes I made AFTER I submitted the PR. I'll get it corrected.

**Comment by cdunlap** [comment]
I'm sort of new to pull requests, having never done one before. I can't seem to create another one that contains only that change without reverting my master branch. I'd rather create a request at a given commit hash instead. I think since this one is open it is preventing me from creating a new one that contains this commit hash. Can you just reject this one and I'll make a new one?

**Comment by vbauer** [comment]
@cdunlap Yes, ofc. :)

**Comment by cdunlap** [comment]
Thank you! I made a new branch and put the proposed changes on that one instead of creating a pull request from my master--which has changes you probably don't want. Check out #30

**Pull request closed without merging**
